#!/bin/bash
set -ev

# It should automatically detect that dependencies are missing, including SDL
# etc., and build them from scratch.
mkdir build && cd build
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DMAGNUM_WITH_ANIMATED_GIF_EXAMPLE=ON \
    -DMAGNUM_WITH_ARCBALL_EXAMPLE=ON \
    -DMAGNUM_WITH_AREALIGHTS_EXAMPLE=ON \
    -DMAGNUM_WITH_AUDIO_EXAMPLE=OFF \
    -DMAGNUM_WITH_BOX2D_EXAMPLE=OFF \
    -DMAGNUM_WITH_BULLET_EXAMPLE=OFF \
    -DMAGNUM_WITH_CUBEMAP_EXAMPLE=ON \
    -DMAGNUM_WITH_DART_EXAMPLE=OFF \
    -DMAGNUM_WITH_FLUIDSIMULATION2D_EXAMPLE=OFF \
    -DMAGNUM_WITH_FLUIDSIMULATION3D_EXAMPLE=OFF \
    -DMAGNUM_WITH_IMGUI_EXAMPLE=OFF \
    -DMAGNUM_WITH_MOTIONBLUR_EXAMPLE=ON \
    -DMAGNUM_WITH_MOUSEINTERACTION_EXAMPLE=ON \
    -DMAGNUM_WITH_OCTREE_EXAMPLE=ON \
    -DMAGNUM_WITH_OVR_EXAMPLE=OFF \
    -DMAGNUM_WITH_PICKING_EXAMPLE=ON \
    -DMAGNUM_WITH_PRIMITIVES_EXAMPLE=ON \
    -DMAGNUM_WITH_RAYTRACING_EXAMPLE=ON \
    -DMAGNUM_WITH_SHADOWS_EXAMPLE=ON \
    -DMAGNUM_WITH_TEXT_EXAMPLE=ON \
    -DMAGNUM_WITH_TEXTUREDQUAD_EXAMPLE=ON \
    -DMAGNUM_WITH_TEXTUREDTRIANGLE_VULKAN_EXAMPLE=OFF \
    -DMAGNUM_WITH_TRIANGLE_EXAMPLE=ON \
    -DMAGNUM_WITH_TRIANGLE_PLAIN_GLFW_EXAMPLE=OFF \
    -DMAGNUM_WITH_TRIANGLE_SOKOL_EXAMPLE=OFF \
    -DMAGNUM_WITH_TRIANGLE_VULKAN_EXAMPLE=OFF \
    -DMAGNUM_WITH_VIEWER_EXAMPLE=ON \
    -G Ninja
ninja $NINJA_JOBS
