group=data

[file]
filename=/home/mosra/Data/models/glTF-Sample-Models-master/2.0/Buggy/glTF-Binary/Buggy.glb
# filename=/home/mosra/Data/models/gltf/Buggy.glb
#filename=/home/mosra/Downloads/sceneLobbyTiled.glb
alias=Buggy.glb
